---
- name: Configure ocemr
  template:
    src: ocemr_settings.py.j2
    dest: /etc/ocemr/settings.py
    owner: root
    group: root
  when: app_server
  notify:
    - Restart Apache2

- name: Super User Exists?
  command: echo "from django.contrib.auth import get_user_model; User = get_user_model(); print(User.objects.filter(username='{{ ocemr.admin_name }}').count()>0)" | python /usr/share/ocemr/apps/ocemr/manage.py shell
  args:
    chdir: "/usr/share/ocemr/apps"
  environment:
    DJANGO_SETTINGS_MODULE: "ocemr.settings"
    PYTHONPATH: "/usr/share/ocemr/apps"
  register: superuser_existed

- name: Create Super User
  django_manage: command="createsuperuser --noinput --username={{ ocemr.admin_name }} --email={{ ocemr.admin_email }}"
                 app_path="/usr/share/ocemr/apps"
                 settings="ocemr.settings"
  when: not superuser_existed

- name: Change Super User Password
  expect:
    command: ocemr-manage changepassword {{ ocemr.admin_name }}
    responses:
      (?i)password: "{{ ocemr.admin_pass }}"

